apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-index-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-index
  template:
    metadata:
      labels:
        app: nginx-index
    spec:
      containers:
      - name: nginx-index
        image: mrpdockerhub/nginx-index:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-index-service
spec:
  selector:
    app: nginx-index
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: NodePort

